### ISSUE TITLE
Problem on case when eps = 1

### ISSUE THREAD

**Issue by Sarimuko** [max-andr/provably-robust-boosting#1]
Hi,
I'm trying to reproduce some results reported in your paper.
When I tried the sample code in your readme, I found that when increasing the eps to a larger one, like 0.8 or 1.0(pretty large considering the data has been scaled to [0,1]), upper bound of robust test error is reported to be equal to standard error, which seems strange.

Thanks.

**Comment by max-andr** [comment]
Hi,

Thanks for the interest in our paper.

I see your point that with eps=1.0 one can change any data point to any other, thus one would expect to see that the upper bounds on the robust test error go to 100%. It's true with one exception - when the classifier is constant. And this is indeed what happens. If you add `print(weak_learner)` to the code snippet, you can see what happens with eps=1.0:
```
Tree: if x[6] < 0.2959: -0.3163 else -0.3163    Tree: if x[2] < 0.4098: -0.3163 else -0.3163    Tree: if x[6] < 0.2959: -0.3163 else -0.3163    Tree: if x[2] < 0.4098: -0.3163 else -0.3163    
Iteration: 1, test error: 35.71%, upper bound on robust test error: 35.71%

Tree: if x[5] < 0.4955: -0.0000 else -0.0000    Tree: if x[5] < 0.4955: -0.0000 else -0.0000    Tree: if x[3] < 0.2525: -0.0000 else -0.0000    Tree: if x[5] < 0.4955: -0.0000 else -0.0000    
Iteration: 2, test error: 35.71%, upper bound on robust test error: 35.71%

Tree: if x[2] < 0.4098: 0.0000 else 0.0000    Tree: if x[6] < 0.2959: 0.0000 else 0.0000    Tree: if x[5] < 0.4955: 0.0000 else 0.0000    Tree: if x[4] < 0.2837: 0.0000 else 0.0000    
Iteration: 3, test error: 35.71%, upper bound on robust test error: 35.71%
```
I.e. all leaf weights are always the same. Thus, we got a constant classifier that always outputs -0.3163, which corresponds to class -1. Note that it's the most popular class and (robust) test error of 35.71% simply corresponds to the percentage of test points of class 1.

Finally, note that this is indeed intended behavior (although it was not hand-coded explicitly, it just follows from the general algorithm) since robust test error of 35.71% is much better than 100%.

**Comment by Sarimuko** [comment]
Got it and thanks.
